experiment: eeg

hyperparameters:
  input_size: 250
  hidden_size: 512
  k_sparse: 32
  num_saes: 2
  learning_rate: 0.001
  num_epochs: 1
  weight_decay: 0.01
  auxiliary_loss_weight: 0
  ensemble_consistency_weight: 0.005
  training_batch_size: 500
  segment_length_sec: 1.0
  lowcut: 0.5
  highcut: 45.0
  filter_order: 5

data:
  eeg_data_url: "https://isip.piconepress.com/projects/nedc/data/tuh_eeg/tuh_eeg/v2.0.1/edf/000/aaaaaaac/"
