experiment: eeg
eeg_subjects: [1]
eeg_runs: [1]
eeg_interval: 0.1
eeg_batch_size: 64
eeg_num_epochs: 50
eeg_learning_rate: 0.0001
eeg_num_layers: 6
eeg_hidden_size: 64
eeg_num_attention_heads: 8
eeg_max_position_embeddings: 20000
eeg_normalize: true
eeg_checkpoint_path: 'eeg_checkpoint.pth'
eeg_model_path: 'eeg_model.pth'
eeg_patience: 5
eeg_lr_patience: 3
