experiment: gpt2

hyperparameters:
  input_size: 768
  hidden_size: 3072
  k_sparse: 6
  num_saes: 10
  learning_rate: 0.001
  num_epochs: 1
  weight_decay: 0.01
  auxiliary_loss_weight: 0
  ensemble_consistency_weight: 0.005
  data_collection_batch_size: 15
  training_batch_size: 500
  num_samples: 1500
