experiment: synthetic
synthetic_epochs: 1
training_batch_size: 5000000
accumulation_steps: 1
learning_rate: [0.001]
input_size: [256]
k_sparse: [32]
hidden_size: [512]
ar: [False]
beta: [5.0]
num_saes: [1]
property: ['x_hat']
