experiment: synthetic
num_epochs: 1
training_batch_size: 10000
learning_rate: [0.01]
dead_feature_threshold: [0.0001]
input_size: [256]
k_sparse: [32]
hidden_size: [512]
ar: [True]
beta: [3]
num_saes: [3]
property: ['x_hat']
