experiment: synthetic
synthetic_epochs: 100
data_batch_size: 100
training_batch_size: 2048
learning_rate: [0.001]
input_size: [256]
l1_coef: [0.005]
hidden_size: [512]
ar: [False]
beta: [5.0]
num_saes: [1]
property: ['x_hat']
